### ISSUE TITLE
PlotData2D : minimum number of points and points removal

### ISSUE THREAD

**Issue by Ersikan** [tschoonj/gtkmm-plplot#16]
I'm using a PlotData2D to plot only points, and not to draw lines between them, and I don't understand why I cannot plot a set of one point, or even no points at all ?

I saw that there is a check at the beginning of the PlotData2D constructor, but is this condition required by the library PLplot ? It seems arbitrary to me, as I saw multiple scatter plots done with PLplot, so it is not required to draw lines, and why would you put a minimum at two points if not to draw at least one line ?

Your library is really awesome and intuitive, but this thing just dumbfounded me.

**Comment by tschoonj** [comment]
Hi @Ersikan!

You are right this seems odd indeed. I think it goes back to very old versions of the library where I forced plots to contain at least one dataset, which I dropped later on. I guess it makes sense to allow datasets to be empty then too.

Many thanks for bringing this to my attention: I will look into fixing this, but if you feel like giving this a try yourself, please feel free to do so!

**Comment by Ersikan** [comment]
I just did a pull request. #17 

Also how would you remove points from a PlotData2D ? The methods get_vector_x() and get_vector_y() just return a copy of the vectors so no modification is possible. And even if it returned a reference, it would not emit signal_change.

**Comment by tschoonj** [comment]
Removing points sounds useful: feel free to add something like to PlotData2D

```cpp
virtual void remove_datapoint(int index);
```

Should be easy to implement... 😉

**Comment by jmiguelsalgado** [comment]
Will remove_datapoint be the way to modify datasets? I'm was looking for a way to create live graphs where I can modify the data points on the fly and I saw this issue on github that may help me achieve the purpose.

**Comment by Ersikan** [comment]
For now the workaround I found was deleting then creating a new PlotData2D each time I needed to change it.

A method to remove a single data point would be useful but not sufficient when you need to remove a lot of points, or even change every datapoint.

It would be nice to have a method to set the dataser of an already existing PlotData2D, therefore keeping the configuration, but changing the data.

**Comment by jmiguelsalgado** [comment]
I am also deleting and creating new PlotData2D for live graphs at the moment. Maybe creating a method like
`replace_dataset(const std::vector<double> &x, const std::vector<double> &y)`
using the std::vector erase and insert methods might work...

**Comment by tschoonj** [comment]
Thanks for your comments... I will implement something like this over the next couple of days... unless you beat me to it of course!
