### ISSUE TITLE
legend boxes clipping when using subscipts.

### ISSUE THREAD

**Issue by AlexB67** [tschoonj/gtkmm-plplot#18]
Hi, I am so glad to have come across your library, thank so much.  

I'd like to ask a question if I may. Perhaps you can suggest a workaround, though I think it may be a small bug.  

The legend box height is a little too small when using subscripts, it clips. It is not that important for now,  perhaps I can even fix it by having a look at the source and suggest a fix in time.

 See the screenshot for details:

https://drive.google.com/file/d/1hsvz1GRRugJSPT-jKx4nB2wLrLOzAc4D/view?usp=sharing

Another feature request would be to make dashed grid lines an option on the graph background, as shown in the screen shot ( I did it by just drawing them using PlotObject2DLine myself for now), though mine do not line up with the axes labels lines currently, but hopefully you get my drift. 

Only having the option to have solid grid lines or none I find I didn't suit my tastes. I find the former too busy on the eye, the latter too bare. I guess it could be added to the list of options with set_box_style is what I had in mind.

set_box_style(Gtk::PLplot::BOX_DASHED_GRID_LINE_OR_SOMETHING_LIKE_THAT);

Awesome work. 😀

Best regards

**Comment by tschoonj** [comment]
Many thanks for the kind words and the screenshot: that is definitely making good use of this library 👍 

Regarding the subscripts: you may want to bring this up with the PLplot developers, as this looks like a bug in their library. Please let me know what they say.

I see how dashed grid lines could make things look nicer. However implementing that may not be trivial as I won't be able to use `env()` any more to draw the box:

https://github.com/tschoonj/gtkmm-plplot/blob/7cf9d43c9362a95b2274bc7520a79446369b997b/gtkmm-plplot/plot2d.cpp#L317-L321

My recommendation would be to write your own class that inherits from `Plot2D`, with its own custom implementation of `draw_plot()`. For inspiration on what to do have a look at the PLplot [implementation](https://github.com/PLplot/PLplot/blob/f580dd5c22f070d44362a777ddb2256f8857f27d/src/plvpor.c) of this method (in C, not C++ but should be similar).

Hope this helps!

**Comment by AlexB67** [comment]
Hi sorry for the delay.   I think you may well be right, since the sub scripting,  italic fonts etc, were implemented using Plplot commands in my code.  

It took me a while to find out how to do it actually, only by having a look at the pl plot documentation did I find out. None of the gtkmm-plplot examples did.   

As an ex theoretical chemist, my boss was always very strict following IUPAC standards in plots, i.e  that variable names must be italic when used on axis labels and legends, just as they are in printed equations, and, IMO it looks better anyway :) 

Gladly I was able to implements it easily,  but in the process came across the subscript overlapping the legend box ( bug ).

I can probably work around it if i had to,  perhaps even scale the font a little smaller if that can be done easily,  but for now I'll leave it and raise it with the plplot people. 

If you wish you can close this issue. For sure I'll let you know when it gets fixed by the PLplot team.

Best regards,

Alex.

**Comment by tschoonj** [comment]
Ok thanks for your comment. Hope they will come up with a fix quickly!
