### ISSUE TITLE
Add support for meson

### ISSUE THREAD

**Issue by tschoonj** [tschoonj/gtkmm-plplot#22]
Building with meson is cool, autotools not so much.

**Comment by AlexB67** [comment]
Nice, I would like to see that with plplot build. :+1:

**Comment by tschoonj** [comment]
This is now complete and will be included in the next release.

**Comment by AlexB67** [comment]
Thank you kindly/ Hartelijk bedankt.  :)

**Comment by tschoonj** [comment]
Fixed in #26
