### ISSUE TITLE
Requested device extcairo not available

### ISSUE THREAD

**Issue by ZhuYanzhen1** [tschoonj/gtkmm-plplot#46]
&nbsp;&nbsp;&nbsp;&nbsp;Hi, I am building and using the Gtkmm-Plplot 2.5.0 project on Ubuntu 22.04. I installed the plplot library via the command apt install meson libplot-dev, however it installs the library version 1.15.0. The process of building and installing Gtkmm-Plplot does not report any errors, but when I use it I am prompted with a `Requested device extcairo not available` error. 
&nbsp;&nbsp;&nbsp;&nbsp;I used example 1 and compiled it using the command `g++ test.cc -o program 'pkg-config --cflags --libs gtkmm-plplot-2.0'`.I have not found where the problem is and am seeking help here.

**Comment by tschoonj** [comment]
You need to install the `plplot-driver-cairo` package to get the `extcairo` device

**Comment by ZhuYanzhen1** [comment]
Thank you! This solved the problem I was having perfectly.
