### ISSUE TITLE
Date / time formatting for axes

### ISSUE THREAD

**Issue by Dalan94** [tschoonj/gtkmm-plplot#9]
Thank you for your library. I have been searching for a plot library for GTKmm for a long time.

Is it possible to use date / time formatting for axes like [here in plplot](http://plplot.sourceforge.net/examples.php?demo=29&lbind=C%2B%2B) ?

I couldn't find the option in gtkmm-plplot but I think it could be easy to add because it work on plplot-cpp.

**Comment by tschoonj** [comment]
Hi,

That should indeed not be hard to add support for.

Do you feel like opening a pull request for this?

**Comment by Dalan94** [comment]
OK I will write the code and send a pull request when it will be ready.

**Comment by Dalan94** [comment]
Implemented in #10
